<?php
/**
 * @auther Jo Cichon
 * @author Anthony Gutierrez
 * @auther Mehdi Jokar
 * @auther Sayed Sadat
 *
 *
 * Created 10/19/2023
 * 355/case-management-app/classes/user.php
 * Student class for the Tribal Pathways project
 */

class Student
{
    private $_student_id;   //auto-generated by database
    private $_first_name;   //required
    private $_middle_name;
    private $_last_name;    //required
    private $_ctclink_id;  //required
    private $_cte_program;
    private $_pronouns;
    private $_tribe_name;
    private $_email;
    private $_phone;
    private $_profile_photo;
    private $_file_name;
    private $_clothing_size;
    private $_course_history;
    private $_academic_progress;
    private $_financial_needs;
    private $_cases;    //array of cases

    /**
     * @param $_first_name
     * @param $_middle_name
     * @param $_last_name
     * @param $_ctclink_id
     */
    public function __construct($_first_name, $_middle_name, $_last_name, $_ctclink_id)
    {
        $this->_first_name = $_first_name;
        $this->_middle_name = $_middle_name;
        $this->_last_name = $_last_name;
        $this->_ctclink_id = $_ctclink_id;
    }

    /**
     * @return mixed
     */
    public function getStudentId()
    {
        return $this->_student_id;
    }

    /**
     * @param mixed $student_id
     */
    public function setStudentId($student_id)
    {
        $this->_student_id = $student_id;
    }

    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->_first_name;
    }

    /**
     * @param mixed $first_name
     */
    public function setFirstName($first_name)
    {
        $this->_first_name = $first_name;
    }

    /**
     * @return mixed
     */
    public function getMiddleName()
    {
        return $this->_middle_name;
    }

    /**
     * @param mixed $middle_name
     */
    public function setMiddleName($middle_name)
    {
        $this->_middle_name = $middle_name;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->_last_name;
    }

    /**
     * @param mixed $last_name
     */
    public function setLastName($last_name)
    {
        $this->_last_name = $last_name;
    }

    /**
     * @return mixed
     */
    public function getCtclinkId()
    {
        return $this->_ctclink_id;
    }

    /**
     * @param mixed $ctclink_id
     */
    public function setCtclinkId($ctclink_id)
    {
        $this->_ctclink_id = $ctclink_id;
    }

    /**
     * @return mixed
     */
    public function getCteProgram()
    {
        return $this->_cte_program;
    }

    /**
     * @param mixed $cte_program
     */
    public function setCteProgram($cte_program)
    {
        $this->_cte_program = $cte_program;
    }

    /**
     * @return mixed
     */
    public function getPronouns()
    {
        return $this->_pronouns;
    }

    /**
     * @param mixed $pronouns
     */
    public function setPronouns($pronouns)
    {
        $this->_pronouns = $pronouns;
    }

    /**
     * @return mixed
     */
    public function getTribeName()
    {
        return $this->_tribe_name;
    }

    /**
     * @param mixed $tribe_name
     */
    public function setTribeName($tribe_name)
    {
        $this->_tribe_name = $tribe_name;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->_email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email)
    {
        $this->_email = $email;
    }


    /**
     * @return mixed
     */
    public function getClothingSize()
    {
        return $this->_clothing_size;
    }

    /**
     * @param mixed $clothing_size
     */
    public function setClothingSize($clothing_size)
    {
        $this->_clothing_size = $clothing_size;
    }

    /**
     * @return mixed
     */
    public function getCourseHistory()
    {
        return $this->_course_history;
    }

    /**
     * @param mixed $course_history
     */
    public function setCourseHistory($course_history)
    {
        $this->_course_history = $course_history;
    }

    /**
     * @return mixed
     */
    public function getAcademicProgress()
    {
        return $this->_academic_progress;
    }

    /**
     * @param mixed $academic_progress
     */
    public function setAcademicProgress($academic_progress)
    {
        $this->_academic_progress = $academic_progress;
    }

    /**
     * @return mixed
     */
    public function getFinancialNeeds()
    {
        return $this->_financial_needs;
    }

    /**
     * @param mixed $financial_needs
     */
    public function setFinancialNeeds($financial_needs)
    {
        $this->_financial_needs = $financial_needs;
    }

    /**
     * @return mixed
     */
    public function getCases()
    {
        return $this->_cases;
    }

    /**
     * @param mixed $cases
     */
    public function setCases($cases)
    {
        $this->_cases = $cases;
    }

    /**
     * @return mixed
     */
    public function getPhone()
    {
        return $this->_phone;
    }

    /**
     * @param mixed $phone
     */
    public function setPhone($phone)
    {
        $this->_phone = $phone;
    }

    /**
     * @return mixed
     */
    public function getProfilePhoto()
    {
        return $this->_profile_photo;
    }

    /**
     * @param mixed $profile_photo
     */
    public function setProfilePhoto($profile_photo)
    {
        $this->_profile_photo = $profile_photo;
    }

    /**
     * @return mixed
     */
    public function getFileName()
    {
        return $this->_file_name;
    }

    /**
     * @param mixed $file_name
     */
    public function setFileName($file_name)
    {
        $this->_file_name = $file_name;
    }



}